// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/ledgerapi/ledger.proto

package ledgerapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The exact data structure the client MUST send over the network.
type TransferRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Source         string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Target         string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Amount         int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"` // Idempotency client-side token!
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TransferRequest) Reset() {
	*x = TransferRequest{}
	mi := &file_api_proto_ledgerapi_ledger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRequest) ProtoMessage() {}

func (x *TransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ledgerapi_ledger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRequest.ProtoReflect.Descriptor instead.
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_ledgerapi_ledger_proto_rawDescGZIP(), []int{0}
}

func (x *TransferRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *TransferRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *TransferRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransferRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

// The exact data structure our gRPC server will return to the client.
type TransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Helpful text detailing a success or reason for failure.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferResponse) Reset() {
	*x = TransferResponse{}
	mi := &file_api_proto_ledgerapi_ledger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferResponse) ProtoMessage() {}

func (x *TransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ledgerapi_ledger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferResponse.ProtoReflect.Descriptor instead.
func (*TransferResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_ledgerapi_ledger_proto_rawDescGZIP(), []int{1}
}

func (x *TransferResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TransferResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Exact data structure for adding accounts...
type InitialiseAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Balance       int64                  `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitialiseAccountRequest) Reset() {
	*x = InitialiseAccountRequest{}
	mi := &file_api_proto_ledgerapi_ledger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitialiseAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitialiseAccountRequest) ProtoMessage() {}

func (x *InitialiseAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ledgerapi_ledger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitialiseAccountRequest.ProtoReflect.Descriptor instead.
func (*InitialiseAccountRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_ledgerapi_ledger_proto_rawDescGZIP(), []int{2}
}

func (x *InitialiseAccountRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *InitialiseAccountRequest) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

// Exact data structure our gRPC server will return to the client for creating accounts...
type InitialiseAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitialiseAccountResponse) Reset() {
	*x = InitialiseAccountResponse{}
	mi := &file_api_proto_ledgerapi_ledger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitialiseAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitialiseAccountResponse) ProtoMessage() {}

func (x *InitialiseAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ledgerapi_ledger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitialiseAccountResponse.ProtoReflect.Descriptor instead.
func (*InitialiseAccountResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_ledgerapi_ledger_proto_rawDescGZIP(), []int{3}
}

func (x *InitialiseAccountResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InitialiseAccountResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto_ledgerapi_ledger_proto protoreflect.FileDescriptor

const file_api_proto_ledgerapi_ledger_proto_rawDesc = "" +
	"\n" +
	" api/proto/ledgerapi/ledger.proto\x12\tledgerapi\"\x82\x01\n" +
	"\x0fTransferRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\"F\n" +
	"\x10TransferResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"P\n" +
	"\x18InitialiseAccountRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x03R\abalance\"O\n" +
	"\x19InitialiseAccountResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xb4\x01\n" +
	"\rLedgerService\x12C\n" +
	"\bTransfer\x12\x1a.ledgerapi.TransferRequest\x1a\x1b.ledgerapi.TransferResponse\x12^\n" +
	"\x11InitialiseAccount\x12#.ledgerapi.InitialiseAccountRequest\x1a$.ledgerapi.InitialiseAccountResponseB,Z*concurrent-bank-ledger/api/proto/ledgerapib\x06proto3"

var (
	file_api_proto_ledgerapi_ledger_proto_rawDescOnce sync.Once
	file_api_proto_ledgerapi_ledger_proto_rawDescData []byte
)

func file_api_proto_ledgerapi_ledger_proto_rawDescGZIP() []byte {
	file_api_proto_ledgerapi_ledger_proto_rawDescOnce.Do(func() {
		file_api_proto_ledgerapi_ledger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_ledgerapi_ledger_proto_rawDesc), len(file_api_proto_ledgerapi_ledger_proto_rawDesc)))
	})
	return file_api_proto_ledgerapi_ledger_proto_rawDescData
}

var file_api_proto_ledgerapi_ledger_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_ledgerapi_ledger_proto_goTypes = []any{
	(*TransferRequest)(nil),           // 0: ledgerapi.TransferRequest
	(*TransferResponse)(nil),          // 1: ledgerapi.TransferResponse
	(*InitialiseAccountRequest)(nil),  // 2: ledgerapi.InitialiseAccountRequest
	(*InitialiseAccountResponse)(nil), // 3: ledgerapi.InitialiseAccountResponse
}
var file_api_proto_ledgerapi_ledger_proto_depIdxs = []int32{
	0, // 0: ledgerapi.LedgerService.Transfer:input_type -> ledgerapi.TransferRequest
	2, // 1: ledgerapi.LedgerService.InitialiseAccount:input_type -> ledgerapi.InitialiseAccountRequest
	1, // 2: ledgerapi.LedgerService.Transfer:output_type -> ledgerapi.TransferResponse
	3, // 3: ledgerapi.LedgerService.InitialiseAccount:output_type -> ledgerapi.InitialiseAccountResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_ledgerapi_ledger_proto_init() }
func file_api_proto_ledgerapi_ledger_proto_init() {
	if File_api_proto_ledgerapi_ledger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_ledgerapi_ledger_proto_rawDesc), len(file_api_proto_ledgerapi_ledger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_ledgerapi_ledger_proto_goTypes,
		DependencyIndexes: file_api_proto_ledgerapi_ledger_proto_depIdxs,
		MessageInfos:      file_api_proto_ledgerapi_ledger_proto_msgTypes,
	}.Build()
	File_api_proto_ledgerapi_ledger_proto = out.File
	file_api_proto_ledgerapi_ledger_proto_goTypes = nil
	file_api_proto_ledgerapi_ledger_proto_depIdxs = nil
}
